name: Keep Flask Server Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # 매 5분마다
  workflow_dispatch:       # 수동 실행도 가능

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Flask server
        run: curl -s https://flask-api-server-wbnf.onrender.com/ping
